INFO:root:languages-folder contains an illegal char. It is being reverted to default name
INFO:root:icons-folder contains an illegal char. It is being reverted to default name
INFO:root:DEBUG mode is on
DEBUG:root:en language is initiated
DEBUG:root:Checking for new launcher versions
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): raw.githubusercontent.com:443
DEBUG:urllib3.connectionpool:https://raw.githubusercontent.com:443 "GET /JeffAxe123/miniProjects/v2//icons/app.png HTTP/1.1" 301 76
DEBUG:urllib3.connectionpool:https://raw.githubusercontent.com:443 "GET /JeffAxe123/miniProjects/v2/icons/app.png HTTP/1.1" 404 14
ERROR:root:couldn't recognize data in image file "assets/icons/app.png"
Traceback (most recent call last):
  File "C:\Users\18lew\jar_launchers\Java miniProjects\launcher.pyw", line 505, in <module>
    mainWindow()
  File "C:\Users\18lew\jar_launchers\Java miniProjects\launcher.pyw", line 260, in mainWindow
    window = sg.Window(core["name"] + "(" + lang["menu.Main"] + ") "+ core["version"], layout).Finalize()
  File "C:\Users\18lew\AppData\Local\Programs\Python\Python39\lib\site-packages\PySimpleGUI\PySimpleGUI.py", line 7942, in Finalize
    self.Read(timeout=1)
  File "C:\Users\18lew\AppData\Local\Programs\Python\Python39\lib\site-packages\PySimpleGUI\PySimpleGUI.py", line 7721, in Read
    results = self._read(timeout=timeout, timeout_key=timeout_key)
  File "C:\Users\18lew\AppData\Local\Programs\Python\Python39\lib\site-packages\PySimpleGUI\PySimpleGUI.py", line 7787, in _read
    self._Show()
  File "C:\Users\18lew\AppData\Local\Programs\Python\Python39\lib\site-packages\PySimpleGUI\PySimpleGUI.py", line 7548, in _Show
    StartupTK(self)
  File "C:\Users\18lew\AppData\Local\Programs\Python\Python39\lib\site-packages\PySimpleGUI\PySimpleGUI.py", line 13024, in StartupTK
    _convert_window_to_tk(window)
  File "C:\Users\18lew\AppData\Local\Programs\Python\Python39\lib\site-packages\PySimpleGUI\PySimpleGUI.py", line 12912, in _convert_window_to_tk
    PackFormIntoFrame(window, master, window)
  File "C:\Users\18lew\AppData\Local\Programs\Python\Python39\lib\site-packages\PySimpleGUI\PySimpleGUI.py", line 12238, in PackFormIntoFrame
    photo = tk.PhotoImage(file=element.Filename)
  File "C:\Users\18lew\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 4063, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "C:\Users\18lew\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 4008, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: couldn't recognize data in image file "assets/icons/app.png"
INFO:root:Process exited with code 1
